MuseumApp/config/routes.rb
MuseumApp::Application.routes.draw do

devise_for :users
  root "home#index"

  resources :paintings
  resources :museums
  resources :artists
  resources :festivals
  resources :foods

end

MuseumApp/app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :paintings
  has_many :museums, -> { uniq }, through: :paintings
end

MuseumApp/app/models/festival.rb
class Festival < ActiveRecord::Base
  belongs_to :artist
  belongs_to :museum
end

MuseumApp/app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :artist
  belongs_to :museum
end

MuseumApp/app/models/museum.rb
class Museum < ActiveRecord::Base
  has_many :paintings
  has_many :artists, -> { uniq }, through: :paintings
  def foo
    @bar = 42
  end

end

MuseumApp/app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :artist
  belongs_to :museum
end

MuseumApp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

MuseumApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

MuseumApp/app/controllers/artist_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find params[:id]
  end

  def new
    @artist = Artist.new
  end

  def create
    safe_artist = params.require(:artist).permit(:name)
    @artist = Artist.create safe_artist
    redirect_to @artist, notice: "Artist successfully added."
  end
end

MuseumApp/app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController
  def index
    @festivals = Festival.all
  end

  def show
    @festival = Festival.find params[:id]
  end

  def new
    @festival = Festival.new
    @artists = Artist.all
    @museums = Museum.all
  end

  def create
    safe_painting = params.require(:festival).permit(:title, :image_url, :place, :description)
    @festival = Festival.create safe_painting
    redirect_to @festival, notice: "Festival successfully added"
  end
end

MuseumApp/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find params[:id]
  end

  def new
    @food = Food.new
    @artists = Artist.all
    @museums = Museum.all
  end

  def create
    safe_painting = params.require(:food).permit(:title, :image_url, :places, :descript)
    @food = Food.create safe_painting
    redirect_to @food, notice: "Food successfully added"
  end
end

MuseumApp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

MuseumApp/app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  def index
    @museums = Museum.all
  end

  def show
    @museum = Museum.find params[:id]
  end

  def new
    @museum = Museum.new
  end
  
  def create
    safe_museum = params.require(:museum).permit(:name)
    @museum = Museum.create safe_museum
    redirect_to @museum, notice: 'Museum successfully added.'
  end
end

MuseumApp/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings = Painting.all
  end

  def show
    @painting = Painting.find params[:id]
  end

  def new
    @painting = Painting.new
    @artists = Artist.all
    @museums = Museum.all
  end

  def create
    safe_painting = params.require(:painting).permit(:title, :image_url, :artist_id, :desc)
    @painting = Painting.create safe_painting
    redirect_to @painting, notice: "Painting successfully added"
  end
end

MuseumApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MuseumApp/app/helpers/artists_helper.rb
module ArtistsHelper
end

MuseumApp/app/helpers/festivals_helper.rb
module FestivalsHelper
end

MuseumApp/app/helpers/foods_helper.rb
module FoodsHelper
end

MuseumApp/app/helpers/home_helper.rb
module HomeHelper
end

MuseumApp/app/helpers/museums_helper.rb
module MuseumsHelper
end

MuseumApp/app/helpers/paintings_helper.rb
module PaintingsHelper
end

MuseumApp/app/views/artists/_artist.html.erb
<li><%= link_to artist.name, artist %></li>

MuseumApp/app/views/artists/index.html.erb
<section class="row">
  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li class="active">Artists</li>
  </ol>

  <h1>Artists</h1>
  <div class="col-md-6">
  <%= link_to "Add a new artist", new_artist_path %>
    <% @artists.each do |artist| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= link_to artist.name, artist %>
          </div>
        </div>
    <% end %>
  </div>
</section>

MuseumApp/app/views/artists/new.html.erb
<h1>New Artist</h1>
<%= form_for @artist do |f| %>
    <fieldset class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </fieldset>
    <%= f.submit nil, class: "btn btn-primary" %>
    <%= link_to "Back", :back, class: "btn btn-warning" %>
<% end %>

MuseumApp/app/views/artists/show.html.erb
<section class="row">
  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Artists", artists_path %></li>
    <li class="active"><%= @artist.name %></li>
  </ol>
  <h1><%= @artist.name %></h1>

  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Listed Paintings</h2>
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <% @artist.paintings.each do |painting| %>
              <li><%= link_to painting.title, painting %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>On display at</h2>
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <% @artist.museums.each do |museum| %>
              <li><%= link_to museum.name, museum %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

</section>
<div class="row">
  <%= link_to "Back to Artists", artists_path %>
</div>

MuseumApp/app/views/festivals/_festival.html.erb
<li><%= link_to festival.title, festival %></li>

MuseumApp/app/views/festivals/index.html.erb
<section class="row">
  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li class="active">Festivals</li>
  </ol>

  <h1>Festivals</h1>
  <div class="col-md-6">
  <%= link_to "Add a festival", new_festival_path %>
    <% @festivals.each do |festival| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= link_to festival.title, festival %>
          </div>
        </div>
    <% end %>
  </div>
</section>

MuseumApp/app/views/festivals/new.html.erb
<h1>Add a festival</h1>
<div class="row">
  <div class="col-md-6"><%= form_for @festival do |f| %>
        <fieldset>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :image_url %>
            <%= f.url_field :image_url, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :place, "Place" %>
            <%= f.text_field :place, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :description, "Description" %>
            <%= f.text_field :description, class: 'form-control' %>
          </div>
        </fieldset>
        <%= f.submit nil, class: "btn btn-primary" %>
        <%= link_to "Back", :back, class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

MuseumApp/app/views/festivals/show.html.erb
<section class="row">
  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Festivals", festivals_path %></li>
    <li class="active"><%= @festival.title %></li>
  </ol>
  <h1><%= @festival.title %></h1>

  <div class="col-md-6">
    <%= image_tag @festival.image_url, class: "img-responsive" %>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel panel-heading">
        <h2>Happens in: <%= @festival.place %></h2>
      </div>

      <div class="panel panel-body">
        <h3>Description: </h3>
        <ul class="list-unstyled">
          <li><%=  @festival.description %></li>
        </ul>
      </div>
    </div>
  </div>
</section>

<div class="row">
  <%= link_to "Back to all festival", paintings_path %>
</div>

MuseumApp/app/views/foods/_food.html.erb
<li><%= link_to food.title, food %></li>

MuseumApp/app/views/foods/index.html.erb
<section class="row">
  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li class="active">Foods</li>
  </ol>

  <h1>Foods</h1>
  <div class="col-md-6">
  <%= link_to "Add a food", new_food_path %>
    <% @foods.each do |food| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= link_to food.title, food %>
          </div>
        </div>
    <% end %>
  </div>
</section>

MuseumApp/app/views/foods/new.html.erb
<h1>Add a food</h1>
<div class="row">
  <div class="col-md-6"><%= form_for @food do |f| %>
        <fieldset>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :image_url %>
            <%= f.url_field :image_url, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :places, "Place" %>
            <%= f.text_field :places, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :descript, "Description" %>
            <%= f.text_field :descript, class: 'form-control' %>
          </div>
        </fieldset>
        <%= f.submit nil, class: "btn btn-primary" %>
        <%= link_to "Back", :back, class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

MuseumApp/app/views/foods/show.html.erb
<section class="row">
  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Foods", foods_path %></li>
    <li class="active"><%= @food.title %></li>
  </ol>
  <h1><%= @food.title %></h1>

  <div class="col-md-6">
    <%= image_tag @food.image_url, class: "img-responsive" %>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel panel-heading">
        <h2>Popular in: <%= @food.places %></h2>
      </div>

      <div class="panel panel-body">
        <h3>Description: </h3>
        <ul class="list-unstyled">
          <li><%= @food.descript %></li>
        </ul>
      </div>
    </div>
  </div>
</section>

<div class="row">
  <%= link_to "Back to all food", foods_path %>
</div>

MuseumApp/app/views/home/index.html.erb
<div class="row">
  <div class="jumbotron">
    <div class="row">
     <div class="col-md-2">
     </div>
      <div class="col-md-8">
        <%= image_tag('splash.gif', class: 'img-responsive img-rounded jumbo-image') %>
        
      </div>
    </div>
  </div>
</div>

<div class="row featured">
  <div class="panel panel-default col-md-4">

    <h2>Foods and Cuisines</h2>
    <%= link_to content_tag(:span, nil, class: 'glyphicon glyphicon-shopping-cart'), foods_path %>
    <!--<%= link_to "Browse by Artist", artists_path %>-->
  </div>

  <div class="panel panel-default col-md-4">
    <h2>Festivities</h2>
    <%= link_to content_tag(:span, nil, class: 'glyphicon glyphicon-user'), festivals_path %>
  </div>
  <div class="panel panel-default col-md-4">
    <h2>Arts</h2>
    <%= link_to content_tag(:span, nil, class: 'glyphicon glyphicon-picture'), paintings_path %>
  </div>
</div>

MuseumApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cultures</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<section class="container">
  <header class="row">
    <nav class="navbar navbar-pills">
      <div class="navbar-header">
        <%= link_to(image_tag('logo2.png', class: 'logo'), root_path, class: 'pull-left') %>
        <%= link_to "Nice Juan!", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Foods and Cuisines", foods_path %></li>
        <li><%= link_to "Festivities", festivals_path %></li>
        <li><%= link_to "Paintings", paintings_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  <% if notice %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
  <% end %>

  <% if alert %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
  <% end %>

  <%= yield %>
</section>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

MuseumApp/app/views/museums/index.html.erb
<section class="row">
  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li class="active">Museums</li>
  </ol>

  <h1>Museums</h1>
  <div class="col-md-6">
    <%= link_to "Add a new Museum", new_museum_path %>
    <% @museums.each do |museum| %>
        <%= link_to museum do %>
            <div class="panel panel-default">
              <div class="panel-body">
                <%= museum.name %> is currently showcasing <%= pluralize(museum.paintings.count, 'painting') %>
              </div>
            </div>
        <% end %>
    <% end %>
  </div>
</section>

MuseumApp/app/views/museums/new.html.erb
<h1>Add a new Museum</h1>
<%= form_for @museum do |f| %>
  <fieldset class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>
    <%= f.submit nil, class: "btn btn-primary" %>
    <%= link_to "Back", :back, class: "btn btn-warning" %>
<% end %>

MuseumApp/app/views/museums/show.html.erb
<section class="row">
  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Museums", museums_path %></li>
    <li class="active"><%= @museum.name %></li>
  </ol>

  <h1><%= @museum.name %></h1>

  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Artists on display</h2>
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <%= render @museum.artists %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Paintings on display</h2>
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <%= render @museum.paintings %>
        </ul>
      </div>
    </div>
  </div>

  <%= link_to "Back to all museums", museums_path %>
</section>

MuseumApp/app/views/paintings/_painting.html.erb
<li><%= link_to painting.title, painting %></li>

MuseumApp/app/views/paintings/index.html.erb
<section class="row">
  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li class="active">Paintings</li>
  </ol>

  <h1>Arts</h1>
  <div class="col-md-6">
  <%= link_to "Add a painting", new_painting_path %>
    <% @paintings.each do |painting| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= link_to painting.title, painting %>
          </div>
        </div>
    <% end %>
  </div>
</section>

MuseumApp/app/views/paintings/new.html.erb
<h1>Add a painting</h1>
<div class="row">
  <div class="col-md-6"><%= form_for @painting do |f| %>
        <fieldset>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :image_url %>
            <%= f.url_field :image_url, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :artist_id  %>
            <%= f.text_field :artist_id, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :desc %>
            <%= f.text_field :desc, class: 'form-control' %>
          </div>
        </fieldset>
        <%= f.submit nil, class: "btn btn-primary" %>
        <%= link_to "Back", :back, class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

MuseumApp/app/views/paintings/show.html.erb
<section class="row">
  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Paintings", paintings_path %></li>
    <li class="active"><%= @painting.title %></li>
  </ol>
  <h1><%= @painting.title %></h1>

  <div class="col-md-6">
    <%= image_tag @painting.image_url, class: "img-responsive" %>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel panel-heading">
        <h2>Created by: <%= @painting.artist_id %></h2>
      </div>

      <div class="panel panel-body">
        <h3>Description: </h3>
        <ul class="list-unstyled">
          <li><%= @painting.desc %></li>
        </ul>
      </div>
    </div>
  </div>
</section>

<div class="row">
  <%= link_to "Back to all paintings", paintings_path %>
</div>